### ISSUE TITLE
building the project

### ISSUE THREAD

**Issue by Yigit-dev** [jurassicjs/nuxt-scheduler#12]
When I use this package, Nuxt 3 stays here while building.
You can preview this build using node .output/server/index.mjs

and it never exit. This does not allow me to deploy.

![Screenshot 2023-12-30 032320](https://github.com/jurassicjs/nuxt-scheduler/assets/58533866/4208fc22-188a-42ae-95fb-5ca7ac979e7f)

**Comment by rohrig** [comment]
Hi @Yigit-dev , I added a workaround to the readme. 

<img width="890" alt="image" src="https://github.com/jurassicjs/nuxt-scheduler/assets/45824492/7b5a49e3-2415-483d-b3ad-a47f78a02356">
