### ISSUE TITLE
How to handle calling functions that request H3 events

### ISSUE THREAD

**Issue by mattmaddux** [jurassicjs/nuxt-scheduler#14]
I'm needing to run some regular maintenance that requires pulling data from Supabase using [NuxtSupabase](https://supabase.nuxtjs.org/), specifically the [serverServiceRole](https://supabase.nuxtjs.org/usage/services/serversupabaseservicerole).

I've got it working just fine when calling via a route. However, I'm now ready to set it up to run from nuxt-scheduler, and I don't know how to handle the expected H3 event.

Any ideas?

**Comment by rohrig** [comment]
I'm just taking a shot in the dark as I don't know anything about your code. But my first instinct is you would just call whatever underlying function you were calling in your route handler. If you have the logic itself in the route handler, I'd say move it to it's own function, then call it it from the route handler. If it works, then it should be the same if you call it within the nuxtScheduler context. 

Hope that helps. 🙂

**Comment by mattmaddux** [comment]
It was actually the underlying function from the NuxtSupabase library that required the H3 event. They built it assuming server calls would be initiated by a route and I'd prefer not to have to reimplement what they've already done.

But I was able to get around it by essentially having the server call itself with a fetch. A little roundabout, but solved the issue.
