### ISSUE TITLE
Run X times

### ISSUE THREAD

**Issue by joseehilton147** [jurassicjs/nuxt-scheduler#2]
Hello, good work on this, very useful.

I was thinking if is possible to make it run a few times? For example, I only want it to run like 4 to 5 times in an interval of one day or 1 week if success, can be dynamically like that? It's on plans to make an improvement like that without save a temp variable to check how many times the plugin already executed.

**Comment by rohrig** [comment]
For the time being I have no plans to do that. But if you make a pull request with a solution that is opt in I'd be happy to merge it 😄
