### ISSUE TITLE
Is it possible to add timezone to scheduler options?

### ISSUE THREAD

**Issue by vnmtvlv** [jurassicjs/nuxt-scheduler#4]
https://www.npmjs.com/package/node-cron#:~:text=Default%20true%3B-,timezone,-%3A%20The%20timezone%20that

**Comment by rohrig** [comment]
Not yet in the module, but yes, this could be added. If you'd like to add this option feel free to make a Pull Request. I'd be happy to merge it. 🙂 If not, I'll get to it when I have time. Thanks for the suggestion.

**Comment by thetejasmagade** [comment]
Hello, @rohrig ! Can you please tell me more about this issue? I want to make a PR for same. 

Thank you!

**Comment by thetejasmagade** [comment]
Hey, @rohrig ! I made a PR ✅

**Comment by rohrig** [comment]
thanks @thetejasmagade 👍
