### ISSUE TITLE
Impact of edge deployments when using this module

### ISSUE THREAD

**Issue by mklueh** [jurassicjs/nuxt-scheduler#6]
Hello,

What would happen if you would use the Netlify Edge preset from [here](https://nitro.unjs.io/deploy/providers/netlify#netlify-edge-functions)?

Will there be a normal server for the function related to this module in addition to the deployed edge functions, or would the scheduled function be deployed multiple times to the edge servers as well?

**Comment by rohrig** [comment]
@mklueh I don't know. If you test it out, I'd love to know what you find. 

The package is build on node-scheduler, so I'm not familiar with how that's handled in such envirornments. I don't have any experience deploying to the edge.
