### ISSUE TITLE
Documentation is not up-to-date

### ISSUE THREAD

**Issue by mlbiche** [jurassicjs/nuxt-scheduler#8]
It seems that the module has been recently updated. The interface has changed but the documentation has not been updated.

I am mainly thinking of the commit https://github.com/jurassicjs/nuxt-scheduler/commit/19916c58d97f3cc4e953e4674cd1b35d0c3229e6 that changes the `run` method interface. How should it be used now ? How should I define the string `key` ? What is it based on ?

**Comment by rohrig** [comment]
Please update to 0.1.9. I've reverted the changes. My mistake. released a feature that's not quite ready. Sorry for any problems it caused you.
