### ISSUE TITLE
When prerendering and using nuxt-scheduler, build hangs

### ISSUE THREAD

**Issue by truesteps** [jurassicjs/nuxt-scheduler#9]
Heya!

I'm trying to prerender some routes due to me using a service worker and need some cache-ing, but when I combine running the scheduler + prerendering, the process hangs and `yarn build` never finishes.

Nuxt version: 3.7.4
Nuxt-scheduler version: 0.1.9

Nuxt config settings:

```TypeScript
routeRules: {
  // Static generation
  '/': { prerender: true },
  '/login': { prerender: true },
  '/register': { prerender: true },
  // CDN cache rules
  '/manifest.webmanifest': {
    headers: {
      'Content-Type': 'application/manifest+json',
      'Cache-Control': 'public, max-age=0, must-revalidate',
    },
  },
},

nitro: {
  esbuild: {
    options: {
      target: 'esnext',
    },
  },
  prerender: {
    crawlLinks: true,
    failOnError: false,
  }
},
```

**Comment by truesteps** [comment]
For now I use a workaround, where during build i overwrite my `APP_ENV` property to `build` so i can skip starting the scheduler, so I can prerender some routes but still run scheduler.

```TypeScript
const startScheduler = () => {
	// don't run scheduler during build
	if (process.env.APP_ENV === 'build') {
		console.log('[server/plugins/scheduler.ts] Skipping scheduler, don\'t run in build context');
		return;
	}
...
```

**Comment by rohrig** [comment]
@truesteps thanks for reporting. I'm working on some updates. I'll see if I can add something directly to the module for this.

**Comment by truesteps** [comment]
> @truesteps thanks for reporting. I'm working on some updates. I'll see if I can add something directly to the module for this.

Thanks :) I didn't really manage to google anything, but I assume there might be some flag, that is set only when build is running, so maybe you could use that to just not run the scheduler? I don't know if thats a viable solution, but that's kinda how my workaround works for now.

**Comment by Chippd** [comment]
This has been giving me the runaround for weeks, so happy to have found this issue. 
~~@truesteps may I ask how you're overwriting your `APP_ENV` property during the build phase?~~

Got it! For future me, or anyone else struggling with this, truesteps' code above, along with a custom build command `ENV=build npm run build` in my cloud provider is what worked for me.

**Comment by truesteps** [comment]
@Chippd heya! In my package json I have a script called build and it just runs `APP_ENV=build nuxt build` that's all.

**Comment by Chippd** [comment]
That's probably easier than my solution actually! Thanks for the quick reply!

**Comment by truesteps** [comment]
@Chippd no probs :) glad to help

**Comment by Chippd** [comment]
Again, for future me that stumbles across this again. I had to change it from overwriting my ENV variable as I had other logic in my app that broke based on the env not being `development` or `production`. The solution was to add another env variable that I called `IS_BUILD`, and set that to `true` when running the build command. So, the build command in my case now looks like this
`IS_BUILD=true npm run build`

Using this variable we can then control when the scheduler is initiated, and not affect other areas

**Comment by truesteps** [comment]
@Chippd since I had nothing tied to the APP_ENV i just used it but ofcourse you can add your own :) good idea. I was trying to look inside the nuxt hooks/process to figure out, if they "mark" a build running somehow, but I came out of it empty handed, It's a little beyond my knowledge of the framework, but there must be something indicating, that the running context is a build

**Comment by rohrig** [comment]
Added workaround to readme. Thanks guys! 😄
